# Generated by Django 5.0.2 on 2024-03-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_usergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
    ]
