# Generated by Django 5.0.2 on 2024-03-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAccess',
        ),
    ]
