# Generated by Django 5.0.2 on 2024-03-02 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_delete_productaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='max_users',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='min_users',
            field=models.IntegerField(default=1),
        ),
    ]
